version: '3.4'
services:
  zoo1:
    image: zookeeper
    restart: unless-stopped
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
  zoo2:
    image: zookeeper
    restart: unless-stopped
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
  zoo3:
    image: zookeeper
    restart: unless-stopped
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
  kafka:
    image: rucciva/kafka:2.2.0
    build: .
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    restart: unless-stopped
    ports: 
      - 9092:9092
    environment:
      - KAFKA_SERVER_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_SERVER_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_SERVER_ZOOKEEPER_CONNECT=zoo1:2181